# -*- coding: utf-8 -*-
"""Crop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCCieTZl1PEcvd60cg0VxT9SheasFAii
"""

import argparse
import cv2

def crop(image_obj, coords, saved_location, extend_ratio=0, SAVE=False):
    nx = image_obj.shape[1]
    ny = image_obj.shape[0]

    modified_coords = (
        int(coords[0] - extend_ratio * nx),
        int(coords[1] - extend_ratio * ny),
        int(coords[2] + extend_ratio * nx),
        int(coords[3] + extend_ratio * ny)
    )
    cropped_image = image_obj[modified_coords[1]:modified_coords[3], modified_coords[0]:modified_coords[2]]

    if SAVE:
        cv2.imwrite(saved_location, cropped_image)

    return cropped_image

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--image", required=True, help="path to the input image")
    ap.add_argument("-c", "--coords", nargs="+", type=int, required=True, help="path to the input image")
    args = ap.parse_args()

    coords = tuple(args.coords)
    saved_location = './'
    image = cv2.imread(args.image)
    crop_img(image, coords, saved_location)

if __name__ == '__main__':
    main()